version: "3.3"

services:
  app:
   build: 
    context: .
    dockerfile: Dockerfile
   container_name: mern
   ports:
   - "5000:5000"
   volumes:
   - ./src/:/usr/src/app
   depends_on:
   - mongo
   restart: always 

  mongo:
   image: mongo
   container_name: mongodb   
   ports:
   - "27017:27017"
   volumes:
   - ./mongodb:/data/db
   restart: always

